### ISSUE TITLE
5月8号已经不能连接上去，提示异常

### ISSUE THREAD

**Issue by HoursX** [01Sr/fchinanet#11]
南京地区，不知道其他地方能不能连上

**Comment by 01Sr** [comment]
把错误信息贴出来

01sr

________________________________

**Comment by msxfXF** [comment]
+1 确实是，提示“操作失败，请联系400-8898915.。。”

**Comment by msxfXF** [comment]
错误码 62201

**Comment by HoursX** [comment]
62201

1733735097 <notifications@github.com> 于 2018年5月8日周二 11:23写道：

**Comment by HoursX** [comment]
01Sr <notifications@github.com> 于 2018年5月8日周二 11:16写道：

**Comment by heng4719** [comment]
常州地区告急，错误码62201

**Comment by Freedomisgood** [comment]
PS C:\Users\10630\Downloads\下载\fchinanet-master> .\fchinanet.exe -a ************ -p ********
[Info] accout:  ************, password:  ***********, device name:  Mrli-computer
[Error] 操作失败，请直接联系4008898915。错误码【62201】

**Comment by euukey** [comment]
苏州同62201

**Comment by JimFanyi** [comment]
南京62201

**Comment by AresCNZJ** [comment]
镇江同62201

**Comment by CallMeSp** [comment]
+1  南京地区  62201

**Comment by Anapopo** [comment]
我这里表现为获取不到随机密码，估计是接口又更改了。

**Comment by YeomanDu** [comment]
其中安卓版本的也是显示连接异常

**Comment by scoltzero** [comment]
@Anapopo 你的shell版本还是可以用的。我的梅林运行正常。

**Comment by 01Sr** [comment]
@HoursX @msxfXF @1733735097 @heng4719 @Freedomisgood

**Comment by BBTYGL** [comment]
@1733735097你这个是怎么调用的？用bat脚本感觉有点麻烦

**Comment by 01Sr** [comment]
写的一个带界面的，但是只有登录功能，而且体积很大，https://github.com/01Sr/fchinanetUI/releases @1733735097

**Comment by 1733735097** [comment]
常州发来捷报！

**Comment by JimFanyi** [comment]
mac版还是不行啊

**Comment by negales1leo** [comment]
登陆之后出现
[Error] Failed to resolve user info![1].怎么搞。。技术小白

**Comment by 01Sr** [comment]
账号密码不对

在 2018年5月9日，16:04，negales1leo <notifications@github.com<mailto:notifications@github.com>> 写道：


登陆之后出现
[Error] Failed to resolve user info![1].怎么搞。。技术小白

**Comment by BBTYGL** [comment]
更新后用bat脚本调用会报错，按任意键也无法退出。
![ynf56 13ca vrxvx v_1 ob_li](https://user-images.githubusercontent.com/34996057/39804468-a68ed3cc-53a6-11e8-87e4-69cd295e2fcb.jpg)

**Comment by BBTYGL** [comment]
更新后用bat脚本调用会报错，而且按任意键也不能退出。
![ynf56 13ca vrxvx v_1 ob_li](https://user-images.githubusercontent.com/34996057/39804554-ed35ba84-53a6-11e8-9360-e3f0b53cb64b.jpg)

**Comment by Freedomisgood** [comment]
带界面的登不上去.
![3](https://user-images.githubusercontent.com/31088082/39804757-8327beb6-53a7-11e8-8e35-7fc785aa17af.jpg)

**Comment by 01Sr** [comment]
重新下载一次吧，之前的有测试的代码代码没有删

01sr

________________________________

**Comment by 01Sr** [comment]
你把这行粘贴到cmd上运行看看有问题吗

01sr

________________________________

**Comment by 01Sr** [comment]
无用的错误信息已经移除了，昨晚可能是没有保存就编译了，导致最后上传的还是显示错误信息的

**Comment by 01Sr** [comment]
只是简单的网络请求，涉及不到windows的帐号问题吧

01sr

________________________________

**Comment by 01Sr** [comment]
@JimFanyi  现在可以用了吗，不可以的话检查时间吧
