### ISSUE TITLE
62202该怎么做?

### ISSUE THREAD

**Issue by cluom** [01Sr/fchinanet#14]
仅在路由器中会62202
![jl40 ru1 y 8x 9_qiq vx](https://user-images.githubusercontent.com/39139933/39842915-30c6e6dc-541b-11e8-87cf-0dddd662d85c.png)

**Comment by cluom** [comment]
在同一局域网下的win下拨号毫无问题

**Comment by 01Sr** [comment]
我尝试了下，应该是你的路由器时间不准确导致的，自己调整下时间吧

在 2018年5月10日，06:27，cluom <notifications@github.com<mailto:notifications@github.com>> 写道：


仅在路由器中会62202
[jl40 ru1 y 8x 9_qiq vx]<https://user-images.githubusercontent.com/39139933/39842915-30c6e6dc-541b-11e8-87cf-0dddd662d85c.png>

**Comment by 01Sr** [comment]
更新了一版，添加了一个指令可以解决这个问题，这样你不用修正本地时间也可以用了，原理就是我设置了一个很大的时间，所以这个时间不会过期

在 2018年5月10日，06:28，cluom <notifications@github.com<mailto:notifications@github.com>> 写道：


在同一局域网下的win下拨号毫无问题

**Comment by cluom** [comment]
感谢 虽然现在断网了 但是已经显示能正常获取到随机密码了

**Comment by 01Sr** [comment]
那应该就没问题了，你是修改的时间还是用的bt指令

01sr

________________________________

**Comment by cluom** [comment]
感谢 虽然现在断网了 但是已经显示能正常获取到随机密码了

**Comment by 01Sr** [comment]
你需要个代理??

01sr

________________________________
