### ISSUE TITLE
Failed to resolve user info[0]

### ISSUE THREAD

**Issue by Chennvice** [01Sr/fchinanet#18]
![image](https://user-images.githubusercontent.com/39194997/39930449-554fc7d2-556d-11e8-807b-24cbf17b062a.png)
不知道是不是用的姿势不对，求大佬指教

**Comment by 01Sr** [comment]
不是你的姿势不对，是电信又调整了姿势

01sr

________________________________

**Comment by Arthur-Mi** [comment]
同遇到这个问题了

**Comment by HoursX** [comment]
安卓应用已经停止运行

**Comment by 01Sr** [comment]
已更

**Comment by yikexiaoyao** [comment]
大佬，怎么脚本运行只有电脑上网，手机没网
求教

**Comment by Chennvice** [comment]
感谢大佬~

**Comment by smile5555** [comment]
大佬，脚本我也不会用，希望你能继续做个apk.可以装进电脑模拟器里面，这个对于我这种笨的人来说可以操作一下

**Comment by 01Sr** [comment]
我做了个电脑版的界面，主页是有连接的

01sr

________________________________

**Comment by 01Sr** [comment]
手机版还没有改

01sr

________________________________

**Comment by smile5555** [comment]
跪求大佬能做出手机版的，谢谢大佬

**Comment by 01Sr** [comment]
嗯嗯，好的

01sr

________________________________

**Comment by 01Sr** [comment]
https://github.com/01Sr/fchinanet/releases/download/v3.5-beta/LoochaCollege-5.3.6.apk 这是我改的掌大的包，连路由器也没问题@yikexiaoyao
