### ISSUE TITLE
Something about protobuf

### ISSUE THREAD

**Issue by Anapopo** [01Sr/fchinanet#21]
https://github.com/01Sr/fchinanet/blob/6d7a2e1d174883bf401eac26875082fe7646416e/fchinanet.go#L417
这里是不需要 `${SERVER_DID}` 了吗？

这一步需要从 `protobuf` 中获取 `USER_ID` 和 `SERVER_ID` 吗？

**Comment by smile5555** [comment]
大佬，这个脚本我不会搞，apk研究出来了吗

**Comment by 01Sr** [comment]
https://github.com/01Sr/fchinanet/releases/download/v3.5-beta/LoochaCollege-5.3.6.apk 去下载这个吧
