### ISSUE TITLE
5.14无法使用

### ISSUE THREAD

**Issue by z1219176085** [01Sr/fchinanet#23]
5.14是电信又换接口了吗
<img src="https://i.loli.net/2018/05/14/5af8f3cfbc0b1.png" alt="QQ截图20180514102614.png" title="QQ截图20180514102614.png" />

**Comment by heng4719** [comment]
+1,连续打开几次之后会提示连接成功，然鹅打开网页还是天翼宽带的页面。
错误的几次里分别报 : [Error] 100005L707
[Error] 100005L708
[Error] 100005L705
[Error] Y532
之后再打开显示登录成功，然鹅网页还是天翼。
常州地区

**Comment by handsomezhong** [comment]
+1

**Comment by BBTYGL** [comment]
+1

**Comment by 01Sr** [comment]
这次我也不知道电信什么操作，暂时用是掌大修改版应付的吧

**Comment by rua001** [comment]
掌大修改版是哪个？
