### ISSUE TITLE
基于fchinanet的多拨脚本

### ISSUE THREAD

**Issue by VCHECKZEN** [01Sr/fchinanet#25]
[fyoung_multi_dial_4_lede](https://github.com/VCHECKZEN/fyoung_multi_dial_4_lede)
说明：
1.  基于斐讯K3 LEDE固件（需7m以上剩余空间、openwrt环境和mwan3）
2.  严重依赖fchinanet，自行解决fchinanet单拨环境使用
3.  严重依赖mwan3， 自行解决mwan3相关配置
4.  修改fchinanet.go的exit函数，去除等待输入部分，在148行左右
func exit() {
	//fmt.Println("Press any key to exit.")
	//var e byte
	//fmt.Scanf("%b", &e)
	os.Exit(0)
}
5.  按路由架构编译并上传
6.  自行浏览修改fyoung.sh并上传，设置开机自启

**Comment by yikexiaoyao** [comment]
求具体操作
