### ISSUE TITLE
电信又搞事

### ISSUE THREAD

**Issue by MZIchenjl** [01Sr/fchinanet#27]
![image](https://user-images.githubusercontent.com/14719366/40158816-0ef6e2be-59d9-11e8-85dd-a64e2c174e5d.png)

南京电信

似乎电信又升级了接口

**Comment by HeiFl** [comment]
对的，接口又挂了。。。sbchinanet

**Comment by hflsec** [comment]
对的，接口又挂了，，sbchinanet
