### ISSUE TITLE
China Telecom has update their code

### ISSUE THREAD

**Issue by scoltzero** [01Sr/fchinanet#4]
it show us that the password is wrong.Please renew your code.Thx

**Comment by 01Sr** [comment]
Ok,i will fix it as soon as possible

在 2018年4月4日，12:50，scoltzero <notifications@github.com<mailto:notifications@github.com>> 写道：


it show us that the password is wrong.Please renew your code.Thx

**Comment by mo7411629** [comment]
多设备登录不做支持了吗？  😂    安卓版的下线功能也取消了吗   😥

**Comment by 01Sr** [comment]
I have updated  it. @scoltzero 
下线有bug暂时改，多设备上限是三个，目前我的软件只能支持两个设备，但是依旧可以三个设备同时上网，意思就是用官方的方式使电脑上网，外加用我的软件使另外任意两个设备上网，不知道我这样解释你明不明白 @mo7411629 
link: https://github.com/01Sr/fchinanet/releases

**Comment by scoltzero** [comment]
Rogar，I get it. It is meaningless to write an android app, but it is better if you write it. I hope you can fix the bug of disconnection.Thx . You a holly genius, bro.

**Comment by 01Sr** [comment]
The android app has been uploaded with a new function that supports multi-devices online.
does the bug of disconnection  mean the function of offline ,or net disconnect in the state of online?
@scoltzero

**Comment by scoltzero** [comment]
Yes offline.Is it just a bug of android  version?

**Comment by scoltzero** [comment]
Sorry to bother you but some wrong happened again. It seems that the Chinanet's code has changed again, too. My schoolmates and I cannot sign in any more. @01Sr

**Comment by 01Sr** [comment]
I have updated

在 2018年4月11日，12:53，scoltzero <notifications@github.com<mailto:notifications@github.com>> 写道：

some
