### ISSUE TITLE
多账号版本登陆异常

### ISSUE THREAD

**Issue by Olld47** [01Sr/fchinanet#6]
大神，我在使用更新了多账号登陆的版本时会出现拨号异常的问题，我回滚到之前的版本则可以正常使用。

**Comment by 01Sr** [comment]
安卓的 还是电脑的版本 type改为1了吗

**Comment by Olld47** [comment]
电脑端，刚才我又试了新版又可以了，明明早上的时候一直拨号异常来着。。

**Comment by 01Sr** [comment]
嗯嗯，能用就行

在 2018年4月7日，15:44，Olld47 <notifications@github.com<mailto:notifications@github.com>> 写道：


电脑端，刚才我又试了新版又可以了，明明早上的时候一直拨号异常来着。。

**Comment by 01Sr** [comment]
贴下错误信息，和你的运行命令

01sr

________________________________

**Comment by Olld47** [comment]
错误是
`[Error] Failed to resolve user info![1]`
命令是是正常是登陆命令
`fchinanet -a 账号-p 密码`

**Comment by 01Sr** [comment]
加个参数-d,也就是f.exe -a ... -p ... -d然后把信息粘给我

01sr

________________________________

**Comment by Olld47** [comment]
`[Debug] Access: http://test.f-young.cn/
[Debug] Response code:  302
Response header:  map[Allow:[GET,POST,HEAD] Mime-Version:[1.0] Server:[NetEngine Server 1.0] Pragma:[No-Cache] Location:[http://202.102.13.97?wlanuserip=10.163.60.217&mscgip=58.213.239.3&wlanusermac=f4-83-cd-23-3f-2c&userlocation=ethtrunk/18:2122.579]]
[Debug] http://202.102.13.97?wlanuserip=10.163.60.217&mscgip=58.213.239.3&wlanusermac=f4-83-cd-23-3f-2c&userlocation=ethtrunk/18:2122.579
[Debug] Access: https://www.loocha.com.cn:8443/login?1=Android_college_100.100.100
[Debug] Response code:  401
[Error] Failed to resolve user info![1].`
报了这样的错误

**Comment by 01Sr** [comment]
这应该是账号密码有错误吧，也有可能是我的漏洞，你可以用浏览器访问最后一个打印出来的url，填上账号密码后看是否正常。如果那么你的密码是否有什么特别的字符比如?之类的

01sr

________________________________

**Comment by Olld47** [comment]
😂没事了，是舍友偷偷改密码了，没说出来。我还是以为是电信又出问题了，很尴尬，麻烦大神了。
