### ISSUE TITLE
仅供Windows用户实现一键操作参考

### ISSUE THREAD

**Issue by AresCNZJ** [01Sr/fchinanet#9]
首先打扰作者大大，开这个issues是来提醒Windows用户可以用批处理进行一键上下线，
以下操作仅供不会操作的童鞋参考，大佬忽略吧(。・＿・。)ﾉI’m sorry~
1、首先下载作者大大的win版本软件（为了方便我去掉了后缀重命名成“fchinanet”）
2、把它放在C:\Users\目录下（可以随意更改，修改bat的对应路径即可）
3、新建txt文件，命名为“上线”（随意随意哈~）
4、打开输入如下语句：
@echo off
start cmd /k "cd/d C:\Users&&fchinanet -a 把我换成你的账号 -p 把我换成你的密码"
5、保存后修改txt文件类型，改为bat即可食用
6、再次新建txt文件，命名为“下线”（as your wish~）
7、打开输入如下语句：
@echo off
start cmd /k "cd/d C:\Users&&fchinanet -a 把我换成你的账号 -p 把我换成你的密码 -b 0"
8、同步骤5
9、Enjoy it！

**Comment by 01Sr** [comment]
不介意的话，我把你发的链接到readme

**Comment by 1733735097** [comment]
小菜鸟看到这个，灰常开心啊O(∩_∩)O哈哈~

**Comment by 01Sr** [comment]
这是别的老哥写的，可以参考参考😋

在 2018年4月11日，08:30，1733735097 <notifications@github.com<mailto:notifications@github.com>> 写道：


小菜鸟看到这个，灰常开心啊O(∩_∩)O哈哈~

**Comment by Haclankid** [comment]
请问为什么运行后是出现

'fchinanet' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

下载的是 releases v3. 1 中的“fchinanet_win_x86-64.exe”
其他操作都是按写的来的

**Comment by 01Sr** [comment]
fchinanet换成你下的程序名，这里为fchinanet_win_x86-64.exe

在 2018年4月11日，13:29，Haclankid <notifications@github.com<mailto:notifications@github.com>> 写道：

fchinanet_win_x86-64.exe

**Comment by AresCNZJ** [comment]
确保程序名和路径正确，或者也可自行修改

**Comment by Haclankid** [comment]
我是照着这部做了

1、首先下载作者大大的win版本软件（为了方便我去掉了后缀重命名成“fchinanet”）

releases下载的exe的文件名也改了，不过我刚刚试着全部改成“fchinanet_win_x86-64.exe”倒是有效果了，然后

`[Info] accout:  ***** , password:  ***** , device name:  Cottoran
[Info] 844414
[Error] Failed to get qrcode![4]
Press any key to exit.`

Orz，难道说我这用不了这个方法吗

**Comment by 1733735097** [comment]
你们使用的是掌上大学么，作者大大这个是针对掌大这个做的

**Comment by 01Sr** [comment]
貌似有常州的同学，今天突然用不了，但是我这边南京正常，不知道你是什么地区的

在 2018年4月11日，13:36，Haclankid <notifications@github.com<mailto:notifications@github.com>> 写道：


我是照着这部做了

1、首先下载作者大大的win版本软件（为了方便我去掉了后缀重命名成“fchinanet”）

releases下载的exe的文件名也改了，不过我刚刚试着全部改成“fchinanet_win_x86-64.exe”倒是有效果了，然后

[Info] accout: ***** , password: ***** , device name: Cottoran [Info] 844414 [Error] Failed to get qrcode![4] Press any key to exit.

Orz，难道说我这用不了这个方法吗

**Comment by Haclankid** [comment]
常州.....

**Comment by 01Sr** [comment]
嗯嗯，待会研究下

在 2018年4月11日，13:40，Haclankid <notifications@github.com<mailto:notifications@github.com>> 写道：


常州.....

**Comment by Haclankid** [comment]
麻烦了，谢谢

**Comment by 1733735097** [comment]
常州的确崩了。。。刚刚作死下线，就过去二维码失败了。

**Comment by 1733735097** [comment]
获取

**Comment by wjbsyc** [comment]
南邮也炸了，刚刚看了一下客户端
((com.realcloud.loochadroid.http.entity.b)v0_1).setParaName("sign");
((com.realcloud.loochadroid.http.entity.b)v0_1).setContenBody(this._md5(f.ʻ().urlenccode(), String.valueOf(v6), v3, ServerSetting.getServerDeviceId()));
好像有个sign字段是一段md5,不知道是不是跟这个有关

**Comment by 01Sr** [comment]
南邮没问题，我就是南邮的，你下的是最新版吗

在 2018年4月11日，15:10，wjbsyc <notifications@github.com<mailto:notifications@github.com>> 写道：

)

**Comment by wjbsyc** [comment]
是啊，我上午才下的，而且还试着重新编译了一份，那我一会再试试。。。

**Comment by 01Sr** [comment]
各位已更新,android版尚未更新

**Comment by Haclankid** [comment]
连接成功，谢谢

**Comment by 1733735097** [comment]
作者辛苦了

**Comment by negales1leo** [comment]
作者大大，
[Info] accout:  1337××××× , password:  392348 , device name:  DESKTOP-H8389SR
[Error] Get http://pre.f-young.cn/: dial tcp: i/o timeout
Press any key to exit.出现这种情况～求支招（０苏州地区）

**Comment by Arthur-Mi** [comment]
苏州连接成功，感谢大佬

**Comment by 01Sr** [comment]
出现这种问题肯定是你的网络环境有问题，如果用的路由器重置下试试🙃 @negales1leo

**Comment by rua001** [comment]
为什么还是密码获取错误请重新获取密码啊....

**Comment by 01Sr** [comment]
你这个提示明显不是最新版本吧

01sr

________________________________

**Comment by yikexiaoyao** [comment]
虽然运行成功了，但是显示按任意键退出，只能按回车，而且按完不退出，显示C：\\Uers这是怎么回事

**Comment by AresCNZJ** [comment]
右上角直接直接关不就行了。。！

**Comment by yikexiaoyao** [comment]
好吧，希望下次人性化一点，谢谢大佬

**Comment by yishunzhikong** [comment]
四川电信的“SC掌上大学”没法用，显示“failed to resolve user info”

**Comment by euukey** [comment]
Press any key to exit,这个提示我按什么都没关掉窗口啊……

**Comment by euukey** [comment]
用的bat，那有办法解决吗😂




-------- 原始電子郵件 --------
寄件者：01Sr <notifications@github.com>
時間：週五 4月27日 16:24
收件者：01Sr/fchinanet <fchinanet@noreply.github.com>
副本：euukey <euukey@163.com>,Comment <comment@noreply.github.com>
主旨：Re: [01Sr/fchinanet] 仅供Windows用户实现一键操作参考 (#9)

**Comment by 01Sr** [comment]
那就在调用的程序里加代码

01sr

________________________________

**Comment by euukey** [comment]
好的谢谢！

-------- 原始電子郵件 --------
寄件者：01Sr <notifications@github.com>
時間：週五 4月27日 16:34
收件者：01Sr/fchinanet <fchinanet@noreply.github.com>
副本：euukey <euukey@163.com>,Comment <comment@noreply.github.com>
主旨：Re: [01Sr/fchinanet] 仅供Windows用户实现一键操作参考 (#9)

**Comment by Arthur-Mi** [comment]
请问大大，出现错误码62201了，是不是只能够连网线不能够连无线啊？

**Comment by huangaa** [comment]
登录错误出现乱码是什么情况？有大佬回答一下吗

**Comment by JamesPei0916** [comment]
安卓版本如何使用？/
